---
name: drift-plugin-build
run-name: Build Elasticsearch Drift plugin
on:
  push:

## Build and create the project on every push to the project
jobs:
  build:
    strategy:
      matrix:
        es_version:
          - 7.17.0
          - 7.17.1
          - 7.17.2
          - 7.17.3
          - 7.17.4
          - 7.17.5
          - 7.17.6
          - 7.17.7
          - 7.17.8
          - 7.17.9
          - 7.17.10
          - 7.17.11
          - 7.17.12
          - 7.17.13
          - 7.17.14
          - 7.17.15
          - 7.17.16
          - 7.17.17
          - 7.17.18
          - 7.17.19
          - 7.17.20
          - 7.17.21
          - 7.17.22
    runs-on: ubuntu-latest
    container:
      image: quay.io/bluebird/java-builder:0.0.3.jdk-17
    steps:
      - uses: actions/checkout@v4
      - name: Add workspace to git safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Build plugin from source
        run: make ES_VERSION=${{ matrix.es_version }}
      - name: Persist drift-plugin artifacts
        uses: actions/upload-artifact@v4
        with:
          name: es-drift-${{ matrix.es_version }}
          path: drift/target/*.jar
